import Head from 'next/head'
import styles from '../styles/Home.module.css'
 
import RadarChart from "../visualizations/Hexagon.tsx";
import UsaChart from "../visualizations/USA.tsx";

import {ContextProvider} from "../visualizations/Context"

import {useEffect, useState} from "react";
 
import StereotypePlot from "../visualizations/StereotypePlot";
import SankeyDiagram from "../visualizations/SankeyDiagram";
 

import * as d3 from "d3";
import StereotypesFilter from "../visualizations/Stereotypes";
import StereotypeScatter from "../visualizations/StereotypeScatter";


export default function Home() {

  let [killersData, setKillersData] = useState([]);
  let [mapData, setMapData] = useState([]);
  let [victimsData, setVictimsData] = useState([]);
  const [loading1, setLoading1] = useState(true);
  const [loading2, setLoading2] = useState(true);
  const [loading3, setLoading3] = useState(true);

  useEffect(() => {
    d3.json("clean_final.json").then((d) => {
      setKillersData(d);
      setLoading1(false);
    });
    d3.json("testmap.json").then((d) => {
      setMapData(d);
      setLoading2(false);
    });
    d3.csv("victims_by_state.csv").then((d) => {
      setVictimsData(d);
      setLoading3(false);
    });
    return () => undefined;
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ContextProvider>
            <div className={styles.card}>
              <h2>Stereotypes</h2>
              <StereotypeScatter data={killersData}></StereotypeScatter>
            </div>
        </ContextProvider>
      </main>
    </div>
  )

}
